{{- if .Values.ingress.enabled -}}
{{- $fullName := include "fullname" . }}
{{- $httpPort := .Values.service.httpPort }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  labels:
    app: {{ template "name" . }}
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: {{ template "fullname" . }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        {{- if $.Values.ingress.path }}
          - path: {{ $.Values.ingress.path }}
        {{- else if index $.Values.ingress "annotations" }}
          {{- if eq (index $.Values.ingress.annotations "kubernetes.io/ingress.class" | default "") "gce" "alb" "istio" }}
          - path: /*
          {{- else }}{{/* Has annotations but ingress class is not "gce" nor "alb" nor "istio" */}}
          - path: /
          {{- end }}
        {{- else }}{{/* Has no annotations */}}
          - path: /
        {{- end }}
            pathType: Prefix
            backend:
              service: 
                name: {{ $fullName }}
                port:
                  number: {{ $httpPort }}
  {{- else }}
    - host: {{ .Values.server.host  }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: {{ $fullName }}
                port:
                  number: {{ $httpPort }}
    - host: "www.{{ .Values.server.host  }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service: 
                name: {{ $fullName }}
                port:
                  number: {{ $httpPort }}

  {{- end -}}

  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- else }}
  tls:
    - hosts: 
      - {{ .Values.server.host }}
      - "www.{{ .Values.server.host }}"
      secretName: home-secret
  {{- end -}}
    
{{- end -}} 